### ISSUE TITLE
“import MultiScaleDeformableAttention as MSDA”

### ISSUE THREAD

**Issue by YaYiXiBa** [cjw2021/SOV-STG#2]
Hello， I meet this code “import MultiScaleDeformableAttention as MSDA” in your file(models/ops/deformable_transformer_attention/functions/ms_deform_attn_func.py), and it reports an error. Could you please tell me where is the "MultiScaleDeformableAttention" module?

**Comment by Innary** [comment]
Hello,

Thank you for your interest in our project.
To resolve this issue, please follow these steps:
1. Navigate to the deformable_transformer_attention directory in the models folder:
`cd ./models/ops/deformable_transformer_attention/`
2. Run the make.sh script to compile the necessary components:
`sh ./make.sh`

After running this script, the module should be correctly set up, and you should no longer encounter the import error.
